"""Initial revision: todos los modelos sin datos previos

Revision ID: 68ca1c69e3a8
Revises: 
Create Date: 2025-06-05 11:29:26.228484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ca1c69e3a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id_administrador', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_administrador'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categoria',
    sa.Column('id_categoria', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('id_administrador', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id_administrador'], ),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('plato',
    sa.Column('id_plato', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tiempo_preparacion_min', sa.Integer(), nullable=True),
    sa.Column('porciones', sa.Integer(), nullable=True),
    sa.Column('info_nutricional', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('id_categoria', sa.BigInteger(), nullable=False),
    sa.Column('id_administrador', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id_administrador'], ),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_plato')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plato')
    op.drop_table('categoria')
    op.drop_table('administrador')
    # ### end Alembic commands ###
